name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - env:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        TRANSIFEX_API_TOKEN: ${{ secrets.TRANSIFEX_API_TOKEN }}
      run: |
        sudo apt-get install -y gettext &&\
        echo pulling translations from Transifex &&\
        for LANG in he ar en_US; do
            echo $LANG &&\
            curl -sL --user api:$TRANSIFEX_API_TOKEN -X GET "https://www.transifex.com/api/2/project/datacity-ckan/resource/ckanpot/translation/he/?mode=reviewed&file" > ckan/i18n/$LANG.po &&\
            msgfmt -o ckan/i18n/$LANG.mo ckan/i18n/$LANG.po
        done &&\
        echo "${DOCKER_HUB_PASSWORD}" | docker login -u "${DOCKER_HUB_USER}" --password-stdin &&\
        docker build -t datacity/ckan:${GITHUB_SHA} ckan &&\
        docker push datacity/ckan:${GITHUB_SHA} &&\
        docker build -t datacity/cca-operator:${GITHUB_SHA} cca-operator &&\
        docker push datacity/cca-operator:${GITHUB_SHA} &&\
        if [ "${GITHUB_REF}" == "refs/heads/master" ]; then
          docker tag datacity/ckan:${GITHUB_SHA} datacity/ckan:latest &&\
          docker push datacity/ckan:latest &&\
          docker tag datacity/cca-operator:${GITHUB_SHA} datacity/cca-operator:latest &&\
          docker push datacity/cca-operator:latest
        fi &&\
        echo datacity/cca-operator:${GITHUB_SHA} &&\
        echo datacity/ckan:${GITHUB_SHA}
