name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - env:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        TRANSIFEX_API_TOKEN: ${{ secrets.TRANSIFEX_API_TOKEN }}
        DATACITY_K8S_DEPLOY_KEY: ${{ secrets.DATACITY_K8S_DEPLOY_KEY }}
      run: |
        sudo apt-get install -y gettext &&\
        echo pulling translations from Transifex &&\
        for LANG in he ar en_US; do
            echo $LANG &&\
            curl -sL --user api:$TRANSIFEX_API_TOKEN -X GET "https://www.transifex.com/api/2/project/datacity-ckan/resource/ckanpot/translation/$LANG/?mode=default&file" > ckan/i18n/$LANG.po &&\
            msgfmt -o ckan/i18n/$LANG.mo ckan/i18n/$LANG.po
        done &&\
        echo "${DOCKER_HUB_PASSWORD}" | docker login -u "${DOCKER_HUB_USER}" --password-stdin &&\
        docker build -t datacity/ckan:${GITHUB_SHA} ckan &&\
        docker push datacity/ckan:${GITHUB_SHA} &&\
        docker build -t datacity/cca-operator:${GITHUB_SHA} cca-operator &&\
        docker push datacity/cca-operator:${GITHUB_SHA} &&\
        if [ "${GITHUB_REF}" == "refs/heads/master" ]; then
          docker tag datacity/ckan:${GITHUB_SHA} datacity/ckan:latest &&\
          docker push datacity/ckan:latest &&\
          docker tag datacity/cca-operator:${GITHUB_SHA} datacity/cca-operator:latest &&\
          docker push datacity/cca-operator:latest &&\
          if ! git log -1 --pretty=format:"%s" | grep -- --no-deploy; then
            cd `mktemp -d` &&\
            echo "${DATACITY_K8S_DEPLOY_KEY}" > deploy_key &&\
            chmod 400 deploy_key &&\
            export GIT_SSH_COMMAND="ssh -i `pwd`/deploy_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" &&\
            git clone git@github.com:hasadna/datacity-k8s.git &&\
            cd datacity-k8s &&\
            echo "${GITHUB_SHA}" > instances/ckan-cloud-docker-latest-tag.txt &&\
            git config --global user.name "ckan-cloud-docker CI" &&\
            git config --global user.email "ckan-cloud-docker-ci@localhost" &&\
            git add instances/ckan-cloud-docker-latest-tag.txt && git commit -m "automatic update of ckan-cloud-docker" &&\
            git push origin master
          fi
        fi &&\
        echo datacity/cca-operator:${GITHUB_SHA} &&\
        echo datacity/ckan:${GITHUB_SHA}
